name = "TemperateOptimalPowerFlow"
uuid = "f1e0c8a6-be03-497e-b6ff-c3d2eb1ec690"
authors = ["Marc Gillioz"]
version = "0.2.0"

[deps]
DataDrop = "aa547a04-dd37-49ab-8e73-656744f8a8fc"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MathOptInterface = "b8f27783-ece8-5eb3-8dc8-9495eed66fee"
MiniLoggers = "93f3dd0f-005d-4452-894a-a31841fa4078"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[weakdeps]
Gurobi = "2e9cd046-0924-5485-92f1-d5272153d98b"
Ipopt = "b6b21f68-93f8-5de0-b562-5493be1d77c9"

[extensions]
TemperateOptimalPowerFlowGurobiExt = "Gurobi"
TemperateOptimalPowerFlowIpoptExt = "Ipopt"

[compat]
MiniLoggers = "0.5"
OrderedCollections = "1"
MathOptInterface = "1"
Gurobi = "1"
DataDrop = "0.1"
Ipopt = "1"
JSON = "0.21"
julia = "1.10"

[extras]
Ipopt = "b6b21f68-93f8-5de0-b562-5493be1d77c9"
PowerModels = "c36e90e8-916a-50a6-bd94-075b64ef4655"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Ipopt", "PowerModels"]
